//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO_PurchasingUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV1\\SQLEXPRESSDEV1;Initial Catalog=PO_ACCOUNTING;User ID=sa;Password" +
            "=123Blue*;Network Library=dbmssocn")]
        public string PO_ACCOUNTINGConnectionString {
            get {
                return ((string)(this["PO_ACCOUNTINGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=E-PROCUREMENT\\EPROCUREMENT;Initial Catalog=PO_ACCOUNTING;User ID=sa;P" +
            "assword=123Blue*;Network Library=dbmssocn")]
        public string PO_ACCOUNTINGConnectionString1 {
            get {
                return ((string)(this["PO_ACCOUNTINGConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=E-PROCUREMENT\\EPROCUREMENT;Initial Catalog=PO_SUPPLIER;User ID=sa;Pas" +
            "sword=123Blue*;Network Library=dbmssocn")]
        public string PO_SUPPLIERConnectionString {
            get {
                return ((string)(this["PO_SUPPLIERConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV1\\SQLEXPRESSDEV1;Initial Catalog=PO_SUPPLIER;User ID=sa;Password=1" +
            "23Blue*;Network Library=dbmssocn")]
        public string PO_SUPPLIERConnectionString1 {
            get {
                return ((string)(this["PO_SUPPLIERConnectionString1"]));
            }
        }
    }
}
